### ISSUE TITLE
Script failed error that I cannot resolve

### ISSUE THREAD

**Issue by kain000** [cees-elzinga/script.xbmc.hue.ambilight#44]
Hello, I'd like to say first and foremost that I love the idea behind this and actually got to play with the addon for a bit, however it stopped working suddenly.  It would throw a "script failure: Xbmc philips Hue"

The auto configure worked the first time just fine, however ever since the script failure message I have not gotten it to work again.

I have tried uninstalling both the hue addon and the requests.master.  Deleting both and re installing per your instructions, but the result is the same.

I have even uninstalled my xbmc 13 and installed Kodi's latest stable release 14, however I get the same error.  It is almost like something outside of the addon has changed.

the following error is always found in the kodi logs

22:24:12 T:1780  NOTICE: XBMC Hue service started, version: 0.6.2
22:24:12 T:1780  NOTICE: XBMC Hue: DEBUG class Hue: flashing lights
22:24:12 T:1780   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "C:\Users\XBMC\AppData\Roaming\Kodi\addons\script.xbmc.hue.ambilight-master\default.py", line 462, in <module>
                                                hue = Hue(settings, args)
                                              File "C:\Users\XBMC\AppData\Roaming\Kodi\addons\script.xbmc.hue.ambilight-master\default.py", line 121, in

I am not sure what to do with this snipit tho I am sure it is telling me exactly what is wrong.

Any help would be much appreciated.

Thanks!

**Comment by newalpha** [comment]
Have this same issue & feel the same way--- I love this plugin and wish to continue using it, please help! In fact, Ive considered building anther system just to use this add-on... Controlling your house lights, simply by pressing the play button on a video you're watching, best feature ever! 

Repeated same steps as  kain000 (^above^) to no avail,  error script failed! :XBMC Philips Hue 
 :
Thank you kain000 for bringing light to this issue, I love this add-on & want to use it! 

Your help would be very appreciated

Thank you, love XBMC Philips Hue add-on!
