### ISSUE TITLE
ZeroDivisionError in default.py on Fire TV on playback

### ISSUE THREAD

**Issue by f-bader** [cees-elzinga/script.xbmc.hue.ambilight#50]
Hi,

on my Fire TV the ambilight function does not work.
I can connect to the bridge and the inital blink also works well.
But as soon as I start a movie the script fails with an "ZeroDivisionError"

Versioninformation

```
Kodi (14.1 Git:2015-01-30-38e4046-dirty)
Kodi compiled Jan 30 2015 by GCC 4.8.0 for Android ARM 32-bit API level 14 (API level 14)
Running on Amazon AFTB with Android 4.2.2 API level 17
```

Logfile

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <type 'exceptions.ZeroDivisionError'>
    Error Contents: float division
    Traceback (most recent call last):
      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmc.hue.ambilight-master/default.py", line 466, in <module>
        run()
      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmc.hue.ambilight-master/default.py", line 383, in run
        hsvRatios = screen.spectrum_hsv(screen.pixels, screen.capture_width, screen.capture_height)
      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmc.hue.ambilight-master/default.py", line 352, in spectrum_hsv
        overall_value = v / float(i)
    ZeroDivisionError: float division
    -->End of Python script error report<--
```

**Comment by f-bader** [comment]
Seems no longer relevant
